### Local Routes
GET http://localhost:3000/
###
GET http://localhost:3000/api/quests
###
GET http://localhost:3000/api/quests/{{id}}

###
POST http://localhost:3000/api/quests
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Brush Teeth",
  "description": "Keep those white and clean!",
  "difficulty": "easy",
  "category": "health",
  "rewardXp": 1000,
  "isDaily": true,
  "dueDate": "2025-10-24T22:00:00.000Z"
}

###
@id = 68fc500c5c533d40f82d6999
@token = <JWT>

###
PUT http://localhost:3000/api/quests/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Brush Teeth",
  "description": "Keep those white and clean!",
  "difficulty": "easy",
  "category": "health",
  "rewardXp": 1000,
  "isDaily": true,
  "dueDate": "2025-10-24T22:00:00.000Z"
}

###
DELETE http://localhost:3000/api/quests/{{id}}
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/users/me
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/api/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "displayName": "Hyrum",
  "settings": { "theme": "dark" },
  "xp": 120,
  "level": 3
}

###
GET http://localhost:3000/api/users/leaderboard
###
GET http://localhost:3000/api-docs/


### Render Routes
GET https://questlog-api.onrender.com/
###
GET https://questlog-api.onrender.com/api/quests
###
GET https://questlog-api.onrender.com/api/quests/{{id}}

###
POST https://questlog-api.onrender.com/api/quests
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Run 3 miles",
  "description": "Evening run at the track",
  "difficulty": "medium",
  "category": "health",
  "rewardXp": 50,
  "isDaily": true,
  "dueDate": "2025-10-20T18:00:00.000Z"
}

###
PUT https://questlog-api.onrender.com/api/quests/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Brush Teeth",
  "description": "Keep those white and clean!",
  "difficulty": "easy",
  "category": "health",
  "rewardXp": 100,
  "isDaily": true,
  "dueDate": "2025-10-24T22:00:00.000Z"
}

###
DELETE https://questlog-api.onrender.com/api/quests/{{id}}
Authorization: Bearer {{token}}

###
GET https://questlog-api.onrender.com/api/users/me
Authorization: Bearer {{token}}

###
PUT https://questlog-api.onrender.com/api/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "displayName": "Hyrum",
  "settings": { "theme": "dark" },
  "xp": 120,
  "level": 3
}

###
GET https://questlog-api.onrender.com/api/users/leaderboard
###
GET https://questlog-api.onrender.com/api-docs/


### Get Auth0 API Token
POST https://dev-yzdx6qc44dbnutbo.us.auth0.com/oauth/token
Content-Type: application/json

{
  "client_id": "UlKw5Z9ylEU2a1JO59Acu4SrTqeGVpbi",
  "client_secret": "",
  "audience": "https://questlog-api",
  "grant_type": "client_credentials"
}
